- include/utils/user.js
https://gitlab.com/trazi-ventures/white-label/services/account/-/issues/36
> Fix #36 Crash user edit dob

- include/utils/audit.js
- tests/endpoints/audit.js
- tests/endpoints/user-edit.js
https://gitlab.com/trazi-ventures/white-label/services/account/-/issues/47
> Fix json and buffer data audit values

- include/utils/user.js
- tests/endpoints/user-edit.js
Fix setUser state & city; update tests
> Fix #49 - User - set user state and city

- include/database/models/basemodel.js
- include/routes/v1/functions/audit.js
- sdk/README.md
- sdk/Travelling.postman_collection.json
- sdk/node/index.js
- sdk/web/index.mjs
- tests/endpoints/audit.js
https://gitlab.com/trazi-ventures/white-label/services/account/-/issues/50
> Update audit queries

- .gitignore
- include/database/models/basemodel.js
- include/routes/v1/functions/groups.js
- include/routes/v1/groups.js
- sdk/README.md
- sdk/Travelling.postman_collection.json
- sdk/node/index.js
- sdk/web/index.mjs
- tests/endpoints/users-get.js
Implements:
https://gitlab.com/trazi-ventures/white-label/services/account/-/issues/55
https://gitlab.com/trazi-ventures/white-label/services/account/-/issues/56
> Fix #55 get users by group

- include/utils/cookietoken.js
Implements: https://gitlab.com/trazi-ventures/white-label/services/account/-/issues/59
Fixes for Node versions 16.15.1 and 18.4.0
> fixes for node 16.15.1 and 18.4.0

- include/database/models/user.js
- include/routes/v1/functions/users.js
- include/routes/v1/users.js
- include/utils/config.js
- include/utils/user.js
- index.js
- package.json
- sdk/README.md
- sdk/Travelling.postman_collection.json
- sdk/node/index.js
- sdk/web/index.mjs
- tests/endpoints/user-edit.js
Implements: https://gitlab.com/trazi-ventures/white-label/services/account/-/issues/60
> Feature #60 edit user data with dot notation

- include/utils/regex.js
- include/utils/user.js
- tests/endpoints/user-edit.js
Gitlab issue: [Feature #71 user data special chars](https://gitlab.com/trazi-ventures/white-label/services/account/-/issues/71)
> Feature #71 user data special chars

- include/database/models/basemodel.js
- tests/endpoints/audit.js
- tests/endpoints/users-get.js
Implements: https://gitlab.com/trazi-ventures/white-label/services/account/-/issues/70
> Fix #70 Remove hashes from responses

- include/routes/v1/functions/audit.js
- tests/endpoints/audit.js
Implements Gitlab issue: https://gitlab.com/trazi-ventures/white-label/services/account/-/issues/73
> Add domains to audit logs

- include/routes/v1/functions/auth.js
- include/routes/v1/functions/users.js
- include/routes/v1/users.js
- include/utils/regex.js
- package.json
- sdk/node/index.js
- sdk/web/index.mjs
- tests/endpoints/auth-login.js
- tests/endpoints/auth-register.js
- tests/endpoints/user-edit.js
- tests/endpoints/users-get.js
- tests/flow-tests.js
- tests/include/UserContainer.js
- tests/routes.js
Gitlab issue: https://gitlab.com/trazi-ventures/white-label/services/account/-/issues/76
> Fix #76 audit log sensitive data leaks

- include/routes/v1/functions/users.js
- include/utils/auth.js
- include/utils/cookietoken.js
- sdk/node/index.js
- sdk/web/index.mjs
- tests/endpoints/user-edit.js
Gitlab issue: https://gitlab.com/trazi-ventures/white-label/services/account/-/issues/77
> Feature #77 Renew trav token on password change

- include/database/index.js
Gitlab ticket: https://gitlab.com/trazi-ventures/white-label/services/account/-/issues/79
> Fix #79 fix login crash

- include/utils/regex.js
Gitlab issue: https://gitlab.com/trazi-ventures/white-label/services/account/-/issues/81
> Feature #81 User Data allow arrays and objects

- include/routes/v1/audit.js
- include/routes/v1/functions/audit.js
- sdk/README.md
- sdk/Travelling.postman_collection.json
- sdk/node/index.js
- sdk/web/index.mjs
- tests/endpoints/audit.js
Gitlab ticket: https://gitlab.com/trazi-ventures/white-label/services/account/-/issues/48
> Feature #48 Audits of and by user count endpoints

- include/routes/v1/functions/auth.js
Github issue: https://gitlab.com/trazi-ventures/white-label/services/account/-/issues/75
> Fix #75 email lowercase bugs

- include/utils/regex.js
Gitlab issue: https://gitlab.com/trazi-ventures/white-label/services/account/-/issues/85
> Feature #85 User Data allow more special chars

- include/database/models/basemodel.js
- sdk/README.md
- sdk/Travelling.postman_collection.json
- sdk/node/index.js
- sdk/web/index.mjs
Gitlab issue: https://gitlab.com/trazi-ventures/white-label/services/account/-/issues/83
> Feature #83 Whitelist filter range operators

- include/utils/email.js
Gitlab issue: https://gitlab.com/trazi-ventures/white-label/services/account/-/issues/101
> Feature #101 Add data to password recovery email

- include/database/index.js
Gitlab issue: https://gitlab.com/trazi-ventures/white-label/services/account/-/issues/102
> Fix #102 Fix max login attempts account locking

- include/database/models/group.js
- include/server/groupmanager.js
- include/server/router.js
- include/token/index.js
- tests/routes.js
Gitlab issue: https://gitlab.com/trazi-ventures/white-label/services/account/-/issues/88
> Feature #88 Add route redirects
